### ISSUE TITLE
Doesn't work with Python 3.7 on MacOS

### ISSUE THREAD

**Issue by lkraider** [saulpw/vsh#2]
Running on macOS 10.14.6, quite a few issues:

- [ ] `async` is a keyword in the language syntax so all code breaks
- [ ] not all requirements are declared in the package (psutil)
- [ ] vls needs to import pathlib to use `Path`
- [ ] vls columns don't show anything but an upside-down questionmark
- [ ] vtop breaks on:
```
  File "vsh/vdtui.py", line 835, in push
    vs.vd = self
AttributeError: 'list' object has no attribute 'vd'
```
- [ ] vping breaks on line 53 `assert ip == m.group(1)` when trying to ping a hostname

**Comment by saulpw** [comment]
Good catch, this repo has become derelict.  For now I'm going to copy these into the main visidata repo and update them for 2.x, and then deprecate this repo.
